services:
    SilasJoisten\Sonata\MultiUploadBundle\Admin\MultiUploadAdminExtension:
        tags:
            - {name: sonata.admin.extension, target: sonata.media.admin.media}
        autowire: true
