services:
    SilasJoisten\Sonata\MultiUploadBundle\Controller\MultiUploadController:
        arguments:
            $mediaManager: '@sonata.media.manager.media'
            $mediaProviderPool: '@sonata.media.pool'
            $maxUploadSize: '%sonata_multi_upload.max_upload_filesize%'
            $redirectTo: '%sonata_multi_upload.redirect_to%'
        tags: ['controller.service_arguments']
        autowire: true
        public: true

    SilasJoisten\Sonata\MultiUploadBundle\Controller\CreateController:
        arguments: ['@sonata.media.pool']
        public: true
        tags: ['controller.service_arguments']
